apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: odmin
subjects:
- kind: ServiceAccount
  name: jane
  namespace: dev
  apiGroup: ""
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
